development:
 adapter: postgresql
 encoding: unicode
 database: duels_development_sinatra
 pool: 5
 username: postgres
 password:
 host: sinatra_db_1

test:
 adapter: postgresql
 encoding: unicode
 database: duels_test_sinatra
 pool: 5
 username: postgres
 password:
 host: sinatra_db_1
