source "https://rubygems.org"

gem "sinatra"
gem "pg"
gem "activerecord"
gem "sinatra-activerecord"
gem "dotenv"

group :test, :development do
  gem "pry"
end

group :test do
  gem "rspec"
  gem "capybara"
  gem "shoulda-matchers"
  gem "launchy"
  gem "database_cleaner"
  gem "factory_girl"
  gem "poltergeist"
end
