source "https://rubygems.org"

gem "sinatra"
gem "pg"
gem "activerecord"
gem "sinatra-activerecord"
gem "dotenv"

group :test, :development do
  gem "pry"
end

group :test do
  gem "rspec"
  gem "capybara"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "launchy"
end
