version: "3"
services:
  react-build:
    image: kevinlarrabee/react-build:1.0
    build:
      context: ./
      dockerfile: ./services/build/Dockerfile
    restart: unless-stopped
    volumes:
      - ./app:/app
  react-server:
    image: kevinlarrabee/react-server:1.0
    build:
      context: ./
      dockerfile: ./services/server/Dockerfile
    restart: unless-stopped
    ports:
      - "1337:8080"
    volumes:
      - ./app:/app
    depends_on:
      - react-build
