# Basic HTTP server for static bundle
FROM nginx:1.13.5
MAINTAINER kevin larrabee

# RUN apk update && rm -rf /var/cache/apk

# RUN addgroup -S planetexpress \
 # && adduser -S -g planetexpress bender

# USER bender

# WORKDIR /app

CMD ["nginx"]
