version: "3"
services:
  db:
    image: postgres:9.6.5
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data

  server:
    image: kevinlarrabee/sinatra:1.0
    restart: unless-stopped
    ports:
      - "1337:4567"
    volumes:
      - ./app:/sinatra/app
    depends_on:
      - db
