version: "3"
services:
  db:
    image: postgres:9.6.5
  server:
    build: .
    image: kevinlarrabee/sinatra:0.5
    ports:
      - "4567:4567"
    volumes:
      - ./app:/sinatra/app
    depends_on:
      - db
