version: "3"
services:
  db:
    image: postgres:9.6.5
    restart: unless-stopped
  server:
    build: .
    image: kevinlarrabee/sinatra:0.5
    restart: unless-stopped
    ports:
      - "8008:4567"
    volumes:
      - ./app:/sinatra/app
    depends_on:
      - db
